### ISSUE TITLE
Eigencontours only computed over 40k subsamples?

### ISSUE THREAD

**Issue by tding1** [dnjs3594/Eigencontours#3]
Hi, I found your work is very interesting! I have a quick question. It seems that the eigencontours for COCO is computed only over 40000 subsamples based on the following line in the code:

https://github.com/dnjs3594/Eigencontours/blob/cf0859d2890f28e8c5d285328022c664406fbb53/Preprocessing/code_v1_COCO/libs/S2_svd.py#L43

However, in the paper it says that "the proposed eigencontours are determined for all instances in all categories in a training dataset". Since 40k < 110k (size of COCO), which is not "all instances", I wonder which one is correct?

Thanks!

**Comment by dnjs3594** [comment]
I revised this issue
