### ISSUE TITLE
what the means of train_seg.pkl and how to generate it?

### ISSUE THREAD

**Issue by 6098669** [dnjs3594/Eigencontours#8]
1

**Comment by dnjs3594** [comment]
The pickle files include segmentation or bounding box information per image.
Below, contents of pickle files.

*_seg.pickle >> dict(key="image_name", value=list) >> list(len=instance numbers) >>array(id, x1, y1, x2, y2, x3, y3, ...)
*_bb.pickle >> dict(key="image_name", value=list) >> list(len=instance numbers) >>array(x1, y1, x2, y2, id)**
